### ISSUE TITLE
ImportError: No module named 'CommonMark'

### ISSUE THREAD

**Issue by rhunwicks** [conda-forge/recommonmark-feedstock#2]
I am trying to use `recommonmark` with Sphinx inside a `conda` env. My `conf.py` includes:

```
from recommonmark.parser import CommonMarkParser
```

which generates the error

```
ImportError: No module named 'CommonMark'
```

Full steps to recreate on my Ubuntu 16.04.3 environment:

```
conda create -n dummy python==3.5
```

```
Fetching package metadata .............
Solving package specifications: .

Package plan for installation in environment ~/miniconda3/envs/dummy:

The following NEW packages will be INSTALLED:

    ca-certificates: 2017.08.26-h1d4fec5_0   
    certifi:         2017.11.5-py35h9749603_0
    libedit:         3.1-heed3624_0          
    libgcc-ng:       7.2.0-h7cc24e2_2        
    libstdcxx-ng:    7.2.0-h7a57d05_2        
    ncurses:         6.0-h9df7e31_2          
    openssl:         1.0.2n-hb7f436b_0       
    pip:             9.0.1-py35h7e7da9d_4    
    python:          3.5.0-1                 
    readline:        6.2-2                   
    setuptools:      36.5.0-py35ha8c1747_0   
    sqlite:          3.20.1-hb898158_2       
    tk:              8.5.18-0                
    wheel:           0.30.0-py35hd3883cf_1   
    xz:              5.0.5-1                 
    zlib:            1.2.11-ha838bed_2       

Proceed ([y]/n)? y

xz-5.0.5-1.tar 100% |################################| Time: 0:00:00 611.59 kB/s
python-3.5.0-1 100% |################################| Time: 0:00:17   1.07 MB/s
certifi-2017.1 100% |################################| Time: 0:00:00   1.09 MB/s
setuptools-36. 100% |################################| Time: 0:00:00 655.66 kB/s
wheel-0.30.0-p 100% |################################| Time: 0:00:00   1.51 MB/s
pip-9.0.1-py35 100% |################################| Time: 0:00:01   1.17 MB/s
#
# To activate this environment, use:
# > source activate dummy
#
# To deactivate an active environment, use:
# > source deactivate
#
```

```
source activate dummy
conda install -c conda-forge recommonmark
```

```
Fetching package metadata .............
Solving package specifications: .

Package plan for installation in environment ~/miniconda3/envs/dummy:

The following NEW packages will be INSTALLED:

    commonmark:   0.5.4-py_0    conda-forge
    docutils:     0.14-py35_0   conda-forge
    future:       0.16.0-py35_0 conda-forge
    recommonmark: 0.4.0-py_1    conda-forge

Proceed ([y]/n)? y

docutils-0.14- 100% |################################| Time: 0:00:02 331.90 kB/s
future-0.16.0- 100% |################################| Time: 0:00:02 261.61 kB/s
```

```
python
```

```
Python 3.5.0 |Continuum Analytics, Inc.| (default, Oct 19 2015, 21:57:25) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
```

```
from recommonmark.parser import CommonMarkParser
```

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/roger/miniconda3/envs/dummy/lib/python3.5/site-packages/recommonmark/parser.py", line 6, in <module>
    from CommonMark import DocParser, HTMLRenderer
ImportError: No module named 'CommonMark'
>>> 
```

**Comment by rhunwicks** [comment]
I think it is something to do with the fact that conda-forge uses `commonmark` rather than `CommonMark` because if I also do `pip install CommonMark==0.5.4` inside the `conda` env then `recommonmark` works.

After the `pip install`, `conda list` shows:

```
CommonMark                0.5.4                     <pip>
commonmark                0.5.4                      py_0    conda-forge
```

**Comment by ocefpaf** [comment]
This was probably fixed at some point b/c it is pinned to `CommonMark 0.5.4` and that uses `CommonMark`. See https://github.com/conda-forge/recommonmark-feedstock/blob/master/recipe/meta.yaml#L25 and https://github.com/conda-forge/commonmark-feedstock/blob/commonmark0.5.4/recipe/meta.yaml#L34
